# see https://github.com/symfony/recipes/blob/master/symfony/messenger/4.1/config/packages/messenger.yaml
framework:
    messenger:
        transports:
#            amqp: '%env(MESSENGER_DSN)%'

        routing:
#            'App\Message\Command\SendNotification': amqp

        default_bus: command_bus
        buses:
            command_bus:
                middleware:
                    - msgphp.messenger.console_message_receiver
            event_bus:
                middleware:
                    - msgphp.messenger.console_message_receiver
                    - allow_no_handler

services:
    msgphp.messenger.command_bus: '@command_bus'
    msgphp.messenger.event_bus: '@event_bus'
